server: 
   port:
    
thymeleaf: 
    cache: true   
    prefix: classpath:/ templates /
    check-template-location: true
    suffix: 
    encoding: UTF-8
    content-type: 
    model: html5 
    
logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test
       username: root
       password: root

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*